"""New update

Revision ID: 00b2fd1e1e5d
Revises: f98ae2204300
Create Date: 2016-04-03 00:05:48.951904

"""

# revision identifiers, used by Alembic.
revision = '00b2fd1e1e5d'
down_revision = 'f98ae2204300'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('alias', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_column('groups', 'alias')
    ### end Alembic commands ###
